### ISSUE TITLE
problem with macOS 10.12.4 Beta (16E189a)

### ISSUE THREAD

**Issue by durul** [Nightonke/Gitee#10]
Hello,

Gitee does not open macOS 10.12.4 Beta (16E189a).

**Comment by floriangbh** [comment]
Same issue with 10.12.3, can't open Gitee from the status bar !

**Comment by Nightonke** [comment]
I tested Gitee in 10.12.3 (16D32) and everything works well. Gitee's logs locate in `~/Library/Application Support/com.nightonke.VHGithubNotifier/GiteeLogs`. Cound you please send the log files to me(by e-mail(2584541288@qq.com) or link)? Thanks.

**Comment by floriangbh** [comment]
Just clean Application supporting files and Gitee, then reboot and download the latest version and it work :-)

**Comment by Nightonke** [comment]
Nice to hear this. If any bug happens, you can send the log files to me in the path mentioned above.

**Comment by durul** [comment]
Hello, Apple publish new beta and I have tested. It is looking good right now. Test OS X is 10.12.4 Beta (16E191a).
