### ISSUE TITLE
how install on max os

### ISSUE THREAD

**Issue by Stephan14** [Nightonke/Gitee#5]
I am a newer, how to install on my macbook, do you write guidance in README

**Comment by yangyang0507** [comment]
Github Release Page

**Comment by Stephan14** [comment]
Can you give me a url ,I can not find Github Release Page, thanks

**Comment by yangyang0507** [comment]
<img width="1010" alt="qq20170316-090853 2x" src="https://cloud.githubusercontent.com/assets/5666807/23977276/39f0ea2a-0a28-11e7-9ad5-b108faed4a13.png">

**Comment by Stephan14** [comment]
OK Thanks
