### ISSUE TITLE
Wrong Label Frame Problem

### ISSUE THREAD

**Issue by tamarous** [Nightonke/Gitee#7]
In the 2nd tab, the bottom UILabel seemed to have a wrong frame.

![2017-03-14 11 37 31](https://cloud.githubusercontent.com/assets/5081116/23884968/31ba6558-08ab-11e7-913b-156581a4e239.png)

**Comment by hackjutsu** [comment]
Same above. I'm also confused about what this pie chart is for. Is it for the stars we get today, or it's the accumulation of all historic records?

**Comment by ApolloZhu** [comment]
@hackjutsu each part of the pie chart shows the ***TOTAL*** number of stars you get for that repository, if it is not less than the minimum you set.

[![108 Stars](https://cloud.githubusercontent.com/assets/10842684/25596045/3b77452e-2e95-11e7-9a24-cb3a01d92e46.png)](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift)
