### ISSUE TITLE
Missing resources - charts.js

### ISSUE THREAD

**Issue by darrarski** [Nightonke/Gitee#8]
# Summary

One can't compile the app because of missing resources. 

# Steps to reproduce

1. Clone repository
2. Open in Xcode 8.2.1
3. Build

## Expected results:

4. App builds without errors

## Actual result:

4. Compilation error occurs:

> error: [...]/ModernLookOSXSample/echarts.js: No such file or directory

# Description

"Copy bundle resources" build phase for `VHGithubNotifier` target is pointing to `charts.js` file in path `../ModernLook-OSX/ModernLookSample/ModernLookOSXSample` which does not exists (it's outside the repository).

**Comment by FsThatOne** [comment]
+1

**Comment by Nightonke** [comment]
@darrarski @FsThatOne Fixed this in newest commit. Please try to clone the repository again.
